from pygame import USEREVENT


# Custom pygame events
STEP_EVENT = USEREVENT + 1
EAT_APPLE = USEREVENT + 2

START_GAME = USEREVENT + 3
END_GAME = USEREVENT + 4
TIMER_UPDATE = USEREVENT + 5
BACK_TO_MAIN_MENU = USEREVENT + 6

# Game settings
SIZE = 600, 384
FPS = 60
SNAKE_STEP_DELAY = 100
BACKGROUND_COLOR = (0, 205, 102)
